name: Project tests
on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up container
        run: docker build -t task1 .
      - name: Run unit tests
        run: docker run task1 pytest task1/test.py
